### ISSUE TITLE
Eureka: Fatal Error

### ISSUE THREAD

**Issue by ShedGrill** [edge-classic/EDGE-classic#648] opened 2023-12-20 02:40 UTC
Put the included edge-classic.ugh in the ports directory and Eureka loads. However, when attempting to create a new or manage the current loaded map, this error pops up: "/gen_types.ugh(481): unmatched double quote". I searched through gen_types.ugh as well as edge-classic.ugh and the original edge.ugh to no avail. Any ideas?

**Comment by dashodanger** [comment] 2023-12-20 03:12
I am unable to reproduce this, but I am using Windows and built Eureka from its repo. What OS and Eureka version are you using?

**Comment by dashodanger** [comment] 2023-12-20 05:41
I will give it a shot and report back; I'm on Win 10 as well so at least that's the same.

**Comment by dashodanger** [comment] 2023-12-20 05:48
[edge-classic-ugh-fixed.zip](https://github.com/edge-classic/EDGE-classic/files/13723475/edge-classic-ugh-fixed.zip)

The repo has the corrected file as well, but here is a copy in case you aren't syncing with it.

There was indeed a missing quote at the end of the line in question; I'm a bit shocked that Git builds of Eureka did not throw this same error...perhaps the parser is more lenient with these things now. At any rate, if this fixes it for you I can close the issue.

**Closed** 2023-12-20 14:31 UTC
Labels: bug, implementation
